language: go

go:
  - 1.14.x

env:
  global:
    - GO111MODULE=on

services:
  - docker

sudo: required

install:
- go get honnef.co/go/tools/cmd/staticcheck
- go mod download
# run this in cricleci
# - (cd sql ; make start-testenv )

before_script:
- go vet ./...
- go build ./...
- go test -run xxxx ./...

script:
- make verifiers
# run this in circleci
# - go test -v -race -short -coverprofile=coverage.txt -timeout 1800s ./...

after_success:
- bash <(curl -s https://codecov.io/bash)

cache:
  directories:
    - $GOPATH/pkg/mod
    - $HOME/.cache/go-build
