version: "3.5"
services:
    postgres:
        image: postgres
        ports:
          - "5432:5432"
        environment:
          POSTGRES_DB: "datastores"
          POSTGRES_USER: "postgres"
          POSTGRES_PASSWORD: "password123"